/**
 * Emits out/sw.js.
 *
 * RIGHT NOW THIS EMITS A KILL SWITCH, NOT A CACHING WORKER.
 *
 * The caching worker shipped on 14 Sep 2026 broke the live app. The fault was
 * mine and the mechanism is worth writing down, because it is the classic one:
 *
 *   install  -> precache the new build, then skipWaiting()
 *   activate -> delete every cache except the new one, then clients.claim()
 *
 * `skipWaiting` plus `clients.claim` hands control of an ALREADY OPEN page to
 * the new worker, and that page is still running the previous build. Activate
 * had just deleted the previous build's cache. This app is
 * `dynamic(ssr: false)`, so its main component arrives in a lazily loaded
 * chunk: the page then asks for a chunk from a build whose cache no longer
 * exists, the request misses, and the lazy import rejects. White screen.
 *
 * A service worker makes that state persistent. Reloading does not help,
 * because the worker intercepts the reload too, which is why the app could not
 * recover on its own.
 *
 * So this file now emits a worker whose only job is to remove itself and every
 * cache it made. Browsers re-check the worker script on navigation, so a device
 * stuck on the broken worker picks this up and repairs itself.
 *
 * Offline support can come back, but network-first for navigations, without
 * skipWaiting, and tested against a real update from one build to the next
 * rather than only a first install.
 */
import { writeFileSync } from "node:fs"
import { join } from "node:path"

const OUT = "out"

const sw = `// Generated by scripts/build-sw.mjs.
// Kill switch: unregisters itself and clears the caches left by the caching
// worker that shipped on 14 Sep 2026. See the script for what went wrong.
self.addEventListener("install", () => self.skipWaiting())

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      const keys = await caches.keys()
      await Promise.all(keys.map((k) => caches.delete(k)))
      await self.registration.unregister()
      const clients = await self.clients.matchAll({ type: "window" })
      // Reload every open tab so it comes back on the real, uncached app.
      for (const client of clients) client.navigate(client.url)
    })(),
  )
})

// Until the unregister lands, stay completely out of the way: no fetch
// handler means every request goes straight to the network.
`

writeFileSync(join(OUT, "sw.js"), sw)
console.log("sw.js: kill switch emitted (unregisters and clears caches)")
