/**
 * Generates out/sw.js after `next build`.
 *
 * Run as part of the build, never by hand: the precache list is the hashed
 * filenames of a specific build, so a worker generated against a different
 * build would cache 404s.
 *
 * The selection rules live in lib/service-worker.ts with tests. This file only
 * walks the directory and writes the result.
 */
import { readdirSync, statSync, writeFileSync, readFileSync } from "node:fs"
import { join, relative, sep } from "node:path"

const OUT = "out"

/** Every file in the build output, as root-relative URL paths. */
function walk(dir) {
  const found = []
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry)
    if (statSync(full).isDirectory()) found.push(...walk(full))
    else found.push("/" + relative(OUT, full).split(sep).join("/"))
  }
  return found
}

// The rules are TypeScript, and this script runs as plain ESM under node, so
// they are re-declared here rather than imported through a build step. The
// tests in lib/service-worker.test.ts are the contract; keep the two in step.
const NEVER = [".txt", ".map", "/sw.js"]
const PLACEHOLDER = /(^|\/)placeholder[-.]/
const shouldPrecache = (p) =>
  p.startsWith("/") && !NEVER.some((s) => p.endsWith(s) || p === s) && !PLACEHOLDER.test(p)

const precache = [...new Set(walk(OUT).filter(shouldPrecache))].sort()

let hash = 0x811c9dc5
for (const ch of precache.join("\n")) {
  hash ^= ch.charCodeAt(0)
  hash = Math.imul(hash, 0x01000193) >>> 0
}
const CACHE = `pomodoro-${hash.toString(16).padStart(8, "0")}`

const sw = `// Generated by scripts/build-sw.mjs. Do not edit.
// Cache name is derived from the precache list, so an unchanged build keeps
// its cache and a changed one evicts the old on activate.
const CACHE = ${JSON.stringify(CACHE)}
const PRECACHE = ${JSON.stringify(precache, null, 2)}

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting()),
  )
})

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  )
})

self.addEventListener("fetch", (event) => {
  const request = event.request
  if (request.method !== "GET") return
  const url = new URL(request.url)
  if (url.origin !== self.location.origin) return

  // A navigation always resolves to the cached shell. The app is a single
  // static page that renders entirely from localStorage, so the shell is the
  // whole app and there is nothing to go and fetch.
  if (request.mode === "navigate") {
    event.respondWith(
      caches.match("/index.html").then((cached) => cached || fetch(request)),
    )
    return
  }

  // Assets are content-hashed, so a cache hit can never be stale.
  event.respondWith(
    caches.match(request).then((cached) => {
      if (cached) return cached
      return fetch(request)
        .then((response) => {
          if (response.ok && response.type === "basic") {
            const copy = response.clone()
            caches.open(CACHE).then((cache) => cache.put(request, copy))
          }
          return response
        })
        .catch(() => cached)
    }),
  )
})
`

writeFileSync(join(OUT, "sw.js"), sw)

const bytes = precache.reduce((n, p) => n + statSync(join(OUT, p.slice(1))).size, 0)
console.log(
  `sw.js: ${precache.length} files, ${(bytes / 1024 / 1024).toFixed(2)} MB precached, cache ${CACHE}`,
)
